project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - p1_acceso.qmd
    - p2_calidad.qmd
    - p3_salariales.qmd
    - p4_mujeres_diversas.qmd
    - metodologia.qmd

website:
  title: "Radar de Brechas Laborales de Género"
  navbar:
    background: "#6c757d"
    foreground: "#ffffff"
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Metodología"
        href: metodologia.qmd
      - text: "Acceso Laboral"
        href: p1_acceso.qmd
      - text: "Calidad del Empleo"
        href: p2_calidad.qmd
      - text: "Brechas Salariales"
        href: p3_salariales.qmd
      - text: "Mujeres Diversas"
        href: p4_mujeres_diversas.qmd
